lervag/wiki.vim

autoload/wiki/complete.vim
Before this commit completion func returned `-1` which means "cancel
completion with an error" vim and does nothing in neovim. This commit
makes it return `-3` which cancels the completion silently. That
unbreaks neovim which doesn't handle `-1` and proceeds with completion
fails on undefined `s:ctx` variable instead.
=> Silently cancel completion if not link is found

autoload/wiki/page.vim
d9004ae makes `WikiOpen` fail to open or create a page if no `wiki_link_target_map` is set.
=> Fix bug introduced in d9004ae

autoload/wiki/buffer.vim, doc/wiki.txt, plugin/wiki.vim
This PR adds two configuration variables to allow users to choose a subset (local/global) of the default mappings to use. This is useful (to me, at least) because while the buffer-local mappings are nice to have, the global mappings interfere with existing keybindings in my config. I wasn't able to find a good way to enable only the local mappings (setting empty `lhs` values in `g:wiki_mappings_global` almost worked but caused strange `echo` output on loading the plugin); hence, this set of changes.
=> Add options to selectively enable only local/global default mappings

autoload/wiki/tags.vim, doc/wiki.txt, plugin/wiki.vim
This PR adds a configuration variable `g:wiki_tag_format_pattern` to allow users to customize the format of their tags, e.g. if they would prefer a syntax like `#tag1 tag2` to the default `:tag1:tag2:`.
This PR is motivated by, when trying to use other editors for my Wiki files on platforms that do not support Vim (e.g. phones, etc.), running into a lack of support for VimWiki-style tags, though hashtag-tags are more broadly supported.
I've tested the example pattern to support that particular style of tag, and it seems to work correctly (e.g. it doesn't capture headers, link fragments, etc.), but I wouldn't be too surprised if I'd missed an edge case.
If you feel this is feature-creep/otherwise out of scope of the project, no problem.
=> Add support for custom tag formats

autoload/wiki/link.vim, autoload/wiki/nav.vim, doc/wiki.txt, plugin/wiki.vim
_**what:**_ This pull request adds a config option to automatically save files before navigating between wiki links. 
_**why:**_ This is pretty useful for me since I often instinctively follow links even when I've made local changes. In that case, I'd rather the plugin just save the file automatically and follow the link, saving me the trouble of exiting the error message and saving the file manually.
_**how:**_ The proposed solution just sticks a check for the option (`g:wiki_write_on_nav`) in the `wiki#nav#return()` and `wiki#link#open()` functions, and calls `update` if the option is set.
_**testing:**_ I've had this change in my personal wiki for some time now without any hiccups. That said, the change is pretty simple and there may be some edge cases I didn't think about, so please …
=> feat: write_on_nav option

autoload/wiki/tags.vim
My proposal to address issue #98 . Seems to search for tags in all files.  It appears to fix the problem also for the FzF tag search, which apparently uses the same tag list.
=> Extend search for tags in files with all wiki extensions (issue #98)

autoload/wiki/page.vim, doc/wiki.txt
First pass solution for #100, the argparse section `page.vim:300` wasn't having any effect (arguments seemed to be empty, though that seems like a config issue). Let me know what you think -- happy to make changes.
Some notes:
* This enforces a markdown or mediawiki link style syntax, but I didn't see any indication that other link formats were supported. If they are, I can add other regex or we can go in a different direction.
* This matches links that end with an extension `.md` or `.wiki`, it won't work meaningfully if `g:wiki_link_extension`is empty (this can change as well)
@lervag
=> Link Extension Replace for WikiExport

autoload/wiki/complete.vim
In #110 I overlooked omni-completion case when there are 2 ore more links in a single line. This PR fixes it.
=> Fix Asciidoc's omnifunction for many links in a single line

autoload/wiki/link.vim, doc/wiki.txt, plugin/wiki.vim
So, I often press enter when my cursor is over a header (`##`) or a bullet (`-` or `*`) and wiki.vim turns that WORD into a link. As `wiki#link#open` toggles the link, there isn't a suitable remapping for `<CR>`, so I added an option.
=> Added option to not toggle links with WikiLinkOpen

autoload/wiki/page.vim, test/test-page/test-move.vim
These are two tests that demonstrate how WikiPageRename works for moving pages around.  It succeeds if target dir exists and fails if target dir does not exist.  These tests are supporting discussion in issue #107
=> Allow WikiPageRename to move the page to another directory (including creating the directory)

autoload/wiki/tags.vim
Running `WikiTagReload` would produce a duplicate list of tag references in `WikiTagSearch`. Each time running `WikiTagReload` would add another repeated set to the search results.
This patch resets the collection to an empty list when running `WikiTagReload`.
=> fix: prevent duplicate tag list on reload

autoload/wiki/buffer.vim, autoload/wiki/graph.vim, doc/wiki.txt
This feature runs a link search against all files in the wiki and opens a loclist with any wiki links that point to non-existing files. It's good to check for broken links after a migration or to check if any [red links](https://en.wikipedia.org/wiki/Wikipedia:Red_link) need to be updated.
=> feat: add graph search to check for broken links

autoload/wiki/url/wiki.vim, doc/wiki.txt
I wish to use vim to edit my notes but my main notes editor is <https://obsidian.md>. They allow fuzzy links like `[[Bunny]]` goes to a `Bunny.md` file that can exist anywhere in your tree. This is different from wiki.vim link behavior.
Allow users to define a function named `WikiSearchCommand` that takes wiki_root and fname and outputs the transformed fname.
In my vimrc to get wiki.vim to support obsidian links:
```vim
function! WikiSearchCommand(wiki_root, fname)
let files = systemlist(printf('pushd %s && fd -e "md" "%s" |tail -n1 && popd', a:wiki_root, a:fname))
return get(files, 0, a:fname)
endfunction
```
=> create an extension point to let users override wiki page lookups

autoload/wiki/buffer.vim, autoload/wiki/fzf.vim, autoload/wiki/nav.vim, autoload/wiki/page.vim, autoload/wiki/template.vim, autoload/wiki/url/wiki.vim, doc/wiki.txt, plugin/wiki.vim, test/test-templates/Makefile, test/test-templates/template-a.md, test/test-templates/template-d.md, test/test-templates/test.vim
Tasks:
See also #46 for more context and discussion.
Feedback wanted: @Corey-Keller, @gauteh, @jabirali
Note: I think the specs are quite good now. I think the most important thing now is to agree on formats and structure, then we can add more interpolation features later, if we deem it necessary.
=> Add template feature for new pages

autoload/wiki/init.vim, autoload/wiki/u.vim
Explicitly check for iOS to fix terrychou/iVim#205
=> Check for iOS

autoload/wiki/page.vim
Trying to run `:WikiPageRename` asks the confirmation prompt and then the new name, but errors out after that: 
```
Error detected while processing function wiki#page#rename_ask[11]..wiki#page#rename:
line   64:
E119: Not enough arguments for function: bufnr
E15: Invalid expression: bufnr()
Press ENTER or type command to continue
```
I believe the problem is the empty call to `bufnr()` at lines 102 and 118 of ` autoload/wiki/page.vim `. Changing those to `bufnr('')` (like in scratch.vim) fixes the issue.
=> Fix error in :WikiPageRename

autoload/wiki/date.vim
Currently attempting to create a monthly summary by pressing `<leader>wm` leads to an error:
```
Error detected while processing function wiki#journal#freq[16]..wiki#date#format[1]..<SNR>92_date:
line    5:
E766: Insufficient arguments for printf()
```
This attempts to work around this by passing the format of the date  as a parameter to `printf` such that it is not attempting to interpret the date format as parameters to `printf` itself.
=> Support default 'date' on nvim 0.5 on OSX

doc/wiki.txt
I've tried expanding on the function substitution by supplying the predefined function as an example. Initially the example replaced the 'Pre-defined functions' section. However, I think this should remain.
=> Clearfication of substitution functions

autoload/wiki/rx.vim
Modified `wiki#rx#surrounded()` to reverse `a:chars`, which I think is what it was supposed to do anyway, and added patterns for bold+italic and italic+bold.
=> Add bold+italic matching

autoload/wiki/link.vim, autoload/wiki/template.vim
Hi @lervag, I really like your plugin so far! I made a few small changes locally and thought I'd share them:
* I noticed an annoying error if I accidentally hit Return in normal mode when my cursor was on a blank line.
* I had a problem with consecutive user-defined functions not being called in my wiki template
* If there is no text under the cursor, exit early from `wiki#link#follow`(don't attempt to toggle an empty link)
* make the search for user-defined template functions less aggressive, since after the insertion of the result of the function call the length of the variable `l:lines` changes, and `l:c2` can extend beyond the beginning of the next curly-braces defining another custom function.
=> fix: avoid toggling empty links, fix bug where some functions don't get called in template

README.md, autoload/wiki/buffer.vim, autoload/wiki/tags.vim, doc/wiki.txt, test/test-tags/test-custom-yaml.vim, test/test-tags/test-defaults.vim, test/wiki-basic/tagged.wiki
This PR adds functionality to rename tags. Some highlights:
`tags.vim`:
- `wiki#tags#rename(old_tag, new_tag='', rename_to_existing=0)`<br>The main renaming function. The `rename_to_existing` parameter forces a tag to be renamed even if the new name already exists (implemented primarily for non-interactive testing).
- `wiki#tags#rename_ask(old_tag='', new_tag='', ...)`<br>The user-facing rename function, called by the `WikiTagRename` command. Prompts for one or both parameters.
- `wiki#tags#get_tag_names(...)`<br>Returns a list of tag names from the cache. Used for completion by `WikiTagRename`.
- `g:wiki#tags#default_parser.make(taglist, curline='')`<br>Required to construct a new buffer line containing the updated tag name.
`buffer.vim`:
- Command `WikiTagRename`
- Default mapping: …
=> Tag renaming

autoload/wiki/u.vim
#168 fixed terrychou/iVim#205 due to system calls not working during startup; 1459952e92b58b7682c7513338ef47febca5495e regresses back to this bug. This restores the explicit check for iOS to avoid the problem.
=> Restore explicit check for iOS

autoload/wiki/complete.vim, doc/wiki.txt, plugin/wiki.vim, test/test-complete/test-tags.vim, test/test-complete/test-wikilinks.vim, test/wiki-basic/ToC-reference.wiki, test/wiki-basic/ToC.wiki
My wiki files all have the first letter capitalized, which makes case-sensitive searching inconvenient. I added an option `g:wiki_completion_case_sensitive` to optionally do case-insensitive searching.
=> Add option for case-insensitive omnicomplete

autoload/wiki.vim, doc/wiki.txt
Love the work you have put into Wiki.vim.
This is a small change to configure the name of the index page, by using the wiki_index_name variable in the goto_index function.
Thanks for considering it.
=> Use wiki_index_name global to set a custom index page name.

autoload/wiki/buffer.vim, doc/wiki.txt
Created command WikiLinkFollowTab to open the link under cursor in a new tab. No default keybinding is associated. This behavior will be familiar to those used to navigating Zettelkästen via GUI applications, and there is no obvious drawback to including it in the project.
=> Added command to follow link in new tab

autoload/wiki/buffer.vim, doc/wiki.txt
A small addition of an extra setting and a short intro in the docs.
=> Make it possible to customize local journal mappings

autoload/wiki/page.vim
They are supported for the other wiki_map* callbacks.
=> Support funcrefs for g:wiki_map_create_page

autoload/wiki/fzf.vim
When `g:wiki_filetypes` contains more than one file type, the function `wiki#fzf#pages()` only shows files that are in a subdirectory of the wiki root (but no deeper).
The reason seems to be the glob pattern that the function generates. If `g:wiki_filetypes == ['md']`, the pattern looks like this:
**/*.md
If `g:wiki_filetypes == ['md', 'wiki]`, the pattern looks like this:
**/*.{md,wiki}
This makes use of *brace-expansion*. The vim help page for `wildcards` has the following to say:
> Which wildcards are supported depends on the system.
> These are the common ones: […]
It then lists some wildcards, but notably not brace-expansion.
While on my system (Ubuntu 22.04), Neovim 0.7.2 seems to support brace-expansion, it does so in an extremely fickle manner:
```vim
glob('*.md')          " Finds …
```
=> Avoid non-portable glob pattern in `wiki#fzf#pages()`.

doc/wiki.txt
default keymap in doc for WikiGraphRelated corrected.
=> Update wiki.txt: Fix default WikiGraphRelated map

autoload/wiki/date.vim
Only one byte!
I wanted journal entries to be in %Y/%m/%Y-%m-%d format so that if I ever flattened the hierarchy, I wouldn't have to rename any of the files. This broke many commands for the journal because I used %Y twice.
=> Allow %Y to appear multiple times in a journal entry name

autoload/wiki/buffer.vim, doc/wiki.txt, lua/wiki/init.lua, plugin/wiki.vim
> related to: #274 
* Removing `WikiFzf{Pages,Tags,Toc}` in favor of `Wiki{Pages,Tags,Toc}`
This uses on Neovim `vim.ui.select` and on vim `junegunn/fzf`.
* Renaming `WikiPageToc` and `WikiPageLocToc` to `WikiGenerateToc` and `WikiGenerateLocToc`
This is for prefenting user confusion with `WikiToc` and also make more clear the outcome of the command.
`WikiPages`
`WikiTags`
`WikiToc`
`WikiPages`
`WikiTags`
`WikiToc`
=> Adding support for neovim `vim.ui.select`

autoload/wiki/tags.vim
It appears as though we may be killing a reference to `self.collection[o:old_tag]` prematurely, thus causing subsequent tags to be renamed.  Prior to this patch I could only rename tags 2 wiki files at a time.
This PR addresses this by creating a deep copy of the list of tag/file relationships to iterate off of.  We then "pop" off the front of `collection[a:old_tag]` every iteration until we are presumably done.  If `collection[a:old_tag]` is empty, we _then_ remove it from the collection.
=> fix: WikiTagRename failure after so many tags

autoload/wiki/rx.vim, autoload/wiki/toc.vim
fixes: #288
PR changes:
* Makes `WikiToc` works with other filetypes
* Makes `WikiTocGenerate` and `WikiTocGenerateLocal` works with other filetypes
Asciidoc works without problems with `WikiToc`. For `WikiTocGenerate`, since asciidoc supports natively table of contents, I've implemented a minimal check that parse the lines between the first level heading and the next heading, and searches for some special keywords that asciidoc can understand. If no first level heading is found, it is created a new one with the name of the file. Then it will append to it the special keywords. It doesn't do anything if it found everything.
https://user-images.githubusercontent.com/96259932/233493622-c37fd33b-9ee7-42d5-a13e-fcfa3c0db1b3.mov
Org works without problems with `WikiToc`. For `WikiTocGenerate` …
=> Generalize Toc related tasks to function with other filetypes

autoload/wiki/complete.vim, autoload/wiki/link.vim, autoload/wiki/link/word.vim, autoload/wiki/page.vim, doc/wiki.txt, plugin/wiki.vim, test/init.vim, test/test-complete/test-markdown.vim, test/test-init/test-buffer-root.vim, test/test-init/test-proper-extension.vim, test/test-links/test-adoc.vim, test/test-links/test-create-special.vim, test/test-links/test-open-markdown.vim, test/test-links/test-open-orgmode.vim, test/test-markdown/test.vim, test/test-orgmode/test.vim, test/test-page/test-rename-md.vim, test/test-page/test-rename-org.vim, test/test-tags/test-custom-yaml.vim, test/wiki-adoc/minimal.vim
See the discussion in #296. This PR implements a first version of the proposed `g:wiki_link_creation`.
The new option provides a more flexible filetype-dependent behaviour. It deprecates four other options and makes configuring wiki.vim easier for most people. Since the new option provides sensible defaults, it also means most people will require less customization.
The following options are deprecated as the related features are all now _more flexibly_ controlled by `g:wiki_link_creation`:
* g:wiki_map_text_to_link
* g:wiki_map_create_page
* g:wiki_link_extension
* g:wiki_link_target_type
=> Support multi-filetype wikis with g:wiki_link_creation

autoload/wiki/link.vim, autoload/wiki/link/_template.vim, autoload/wiki/link/adoc_link.vim, autoload/wiki/link/adoc_xref_bracket.vim, autoload/wiki/link/adoc_xref_inline.vim, autoload/wiki/link/cite.vim, autoload/wiki/link/date.vim, autoload/wiki/link/md_fig.vim, autoload/wiki/link/ref_shortcut.vim, autoload/wiki/link/word.vim, autoload/wiki/rx.vim, autoload/wiki/template.vim, doc/wiki.txt, plugin/wiki.vim, test/test-links/test-detection.vim, test/wiki-adoc/index.adoc
=> Implement g:wiki_link_default_schemes option

doc/wiki.txt
the example is not corresponding with below and it's an invalid example, should be `md` instead
=> doc: fix example

doc/wiki.txt
Currently, I am a Vimwiki user, but I like the "do one thing and do it well" philosophy. I might give your plugin a try in the future, as the Vimwiki project seems a bit abandoned.
I developed [link.vim](https://github.com/qadzek/link.vim) for Vimwiki, but it might also be useful for `wiki.vim`, at least for users using Markdown syntax and Markdown links.
After briefly installing your plugin, everything seems to work as expected. `:help wiki-link-reference` also confirms that reference-style links are supported.
=> doc: add link.vim

doc/wiki.txt
It seems that two commands in the list of default mappings had an old name.
For another mapping, it looks like only Normal mode was documented.
=> doc: fix list of default mappings

doc/wiki.txt
After the example of `g:wiki_templates`  it is mentioned, that `;` is appended to the source filename. However,  I could not find `;` in the example above.  I assume this part of the doc is outdated. Thus, I suggest to remove this part in the doc.
=> doc: Remove outdated text in g:wiki_templates

autoload/wiki/fzf.vim, doc/wiki.txt, test/example-select-methods/select-methods-fzf.vim
Dear @lervag,
I suggest three improvements for `wiki#fzf#link` which also fixes a bug. I combined them in one pull request, because they depend on each other. 
1. The first commit removes `/` in the beginning of every search query in `wiki#fzf#pages` and `wiki#fzf#links`.
2. Unfortunately in the current state `wiki#fzf#link` does not work for new links, since the `mode` variable is incapsulated in existing pages. The second commit fixes this issue. 
3. The last commit adds a force key for `wiki#fzf#link` similar to the one of `wiki#fzf#pages`. It is worth mentioning that I changed `g:wiki_fzf_pages_force_create_key` to `g:wiki_fzf_force_create_key` to make it usable for both mentioned selecting methods. 
Best regards
=> Improve fzf select

autoload/wiki/url/utils.vim, test/test-links/test-follow-anchored-id.vim, test/test-links/test-follow-anchored.vim, test/wiki-markdown/index.md
Pretty easy fix thanks to how well you've written your code. I suggest adding some more comments to make it easier for people to contribute, though the documentation was an enormous help!
Makes the wiki link handler look for exact, case-sensitive header-id match for anchors. Tested and works great!
=> Added ability to follow anchors to heading-id

plugin/wiki.vim
Ensures `g:wiki_select_method` is evaluated during mapping definition,
allowing `bang_wrapper()` to receive the function name instead of a variable name.
=> fix: pass function name when defining mappings

README.md
If the `wiki.vim` configuration consists solely of `let g:wiki_root = '~/wiki'`, hitting `<leader>ww` actually opens `index.md` instead of `index.wiki`. This behavior changes when `let g:wiki_filetypes = [ 'wiki' ]` is added to the configuration.
In the similar section in `:help wiki-intro-usage` no filename is mentioned, so I've updated `README.md` accordingly.
=> Remove mention of incorrect filename
